### PR TITLE
Shorten the description to 2500 words

### PR DESCRIPTION
**Pull request by wkearn**

### CODE REVIEW

**Comment by wkearn** [comment]
that's 2500 characters, not words.

**Comment by tomhohenstein** [comment]
this looks pretty good - what do you think? Submit it?

**Comment by wkearn** [comment]
I am happy to submit.

What does @Kevin-Mattheus-Moerman think?

**Comment by Kevin-Mattheus-Moerman** [comment]
Looks good.

**Comment by tomhohenstein** [comment]
Submitted it!

**Pull request merged**
